# Generated by Django 6.0.6 on 2026-06-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_director_genre_film_director_film_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genres',
        ),
    ]
