# Generated by Django 6.0.6 on 2026-06-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_genre_film_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.IntegerField(choices=[(1, '⭐️'), (2, '⭐️⭐️'), (3, '⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (5, '⭐️⭐️⭐️⭐️⭐️'), (6, '⭐️⭐️⭐️⭐️⭐️⭐️'), (7, '⭐️⭐️⭐️⭐️⭐️⭐️⭐️'), (8, '⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️'), (9, '⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️'), (10, '⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️')], default=7)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='films.film')),
            ],
        ),
    ]
